trigger:
  branches:
    include:
    - main
    - develop

schedules:
- cron: "0 21 * * *"  # Daily at 9:00 PM UTC
  displayName: Daily Robot Framework Tests
  branches:
    include:
    - main
  always: true

pool:
  name: 'Default'

variables:
  python.version: '3.9'

jobs:
- job: RobotTests
  displayName: 'Robot Framework Tests'
  
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  - script: |
      # Create results directory
      mkdir -p results
      
      # Run Robot Framework tests (without mobile dependencies for now)
      robot \
        --outputdir results \
        --timestampoutputs \
        --include "E2E" \
        tests/
    displayName: 'Run Robot Framework Tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'results/output.xml'
      mergeTestResults: true
      testRunTitle: 'Robot Framework Tests'
    condition: always()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Test Results'
    inputs:
      pathToPublish: 'results'
      artifactName: 'robot-test-results'
    condition: always()

  - task: PowerShell@2
    displayName: 'Send Email Notification'
    inputs:
      targetType: 'inline'
      script: |
        # Simple email notification
        Write-Host "Test execution completed. Email notification would be sent here."
        Write-Host "To enable email notifications, configure EMAIL_USERNAME, EMAIL_PASSWORD, EMAIL_TO, EMAIL_FROM variables."
    condition: always()
